import { contextBridge, ipcRenderer } from 'electron'
import type { ArchiveApi } from '../shared/archiveContracts'

const archiveApi: ArchiveApi = {
  selectImportFiles: () => ipcRenderer.invoke('archive:selectImportFiles'),
  selectBackupExportDestination: () => ipcRenderer.invoke('archive:selectBackupExportDestination'),
  selectBackupExportSource: () => ipcRenderer.invoke('archive:selectBackupExportSource'),
  selectRestoreTargetDirectory: () => ipcRenderer.invoke('archive:selectRestoreTargetDirectory'),
  createBackupExport: (input) => ipcRenderer.invoke('archive:createBackupExport', input),
  restoreBackupExport: (input) => ipcRenderer.invoke('archive:restoreBackupExport', input),
  createImportBatch: (input) => ipcRenderer.invoke('archive:createImportBatch', input),
  listImportBatches: () => ipcRenderer.invoke('archive:listImportBatches'),
  getImportBatch: (batchId) => ipcRenderer.invoke('archive:getImportBatch', { batchId }),
  searchArchive: (input) => ipcRenderer.invoke('archive:search', input),
  logicalDeleteBatch: (batchId) => ipcRenderer.invoke('archive:deleteBatch', { batchId }),
  listCanonicalPeople: () => ipcRenderer.invoke('archive:listCanonicalPeople'),
  getCanonicalPerson: (canonicalPersonId) => ipcRenderer.invoke('archive:getCanonicalPerson', { canonicalPersonId }),
  getPersonTimeline: (canonicalPersonId) => ipcRenderer.invoke('archive:getPersonTimeline', { canonicalPersonId }),
  getPersonGraph: (canonicalPersonId) => ipcRenderer.invoke('archive:getPersonGraph', { canonicalPersonId }),
  listPersonProfileAttributes: (input) => ipcRenderer.invoke('archive:listPersonProfileAttributes', input),
  listProfileAttributeCandidates: (input) => ipcRenderer.invoke('archive:listProfileAttributeCandidates', input),
  approveProfileAttributeCandidate: (queueItemId) => ipcRenderer.invoke('archive:approveProfileAttributeCandidate', { queueItemId }),
  rejectProfileAttributeCandidate: (input) => ipcRenderer.invoke('archive:rejectProfileAttributeCandidate', input),
  undoProfileAttributeDecision: (journalId) => ipcRenderer.invoke('archive:undoProfileAttributeDecision', { journalId }),
  listReviewQueue: (input) => ipcRenderer.invoke('archive:listReviewQueue', input),
  listDecisionJournal: () => ipcRenderer.invoke('archive:listDecisionJournal'),
  listReviewInboxPeople: () => ipcRenderer.invoke('archive:listReviewInboxPeople'),
  listReviewConflictGroups: () => ipcRenderer.invoke('archive:listReviewConflictGroups'),
  listReviewWorkbenchItems: (input) => ipcRenderer.invoke('archive:listReviewWorkbenchItems', input),
  getReviewWorkbenchItem: (queueItemId) => ipcRenderer.invoke('archive:getReviewWorkbenchItem', { queueItemId }),
  approveReviewItem: (queueItemId) => ipcRenderer.invoke('archive:approveReviewItem', { queueItemId }),
  approveSafeReviewGroup: (input) => ipcRenderer.invoke('archive:approveSafeReviewGroup', input),
  rejectReviewItem: (input) => ipcRenderer.invoke('archive:rejectReviewItem', input),
  undoDecision: (journalId) => ipcRenderer.invoke('archive:undoDecision', { journalId }),
  setRelationshipLabel: (input) => ipcRenderer.invoke('archive:setRelationshipLabel', input),
  listEnrichmentJobs: (input) => ipcRenderer.invoke('archive:listEnrichmentJobs', input),
  listEnrichmentAttempts: (input) => ipcRenderer.invoke('archive:listEnrichmentAttempts', input),
  listProviderEgressArtifacts: (jobId) => ipcRenderer.invoke('archive:listProviderEgressArtifacts', { jobId }),
  getDocumentEvidence: (fileId) => ipcRenderer.invoke('archive:getDocumentEvidence', { fileId }),
  rerunEnrichmentJob: (jobId) => ipcRenderer.invoke('archive:rerunEnrichmentJob', { jobId }),
  listStructuredFieldCandidates: (input) => ipcRenderer.invoke('archive:listStructuredFieldCandidates', input),
  approveStructuredFieldCandidate: (queueItemId) => ipcRenderer.invoke('archive:approveStructuredFieldCandidate', { queueItemId }),
  rejectStructuredFieldCandidate: (input) => ipcRenderer.invoke('archive:rejectStructuredFieldCandidate', input),
  undoStructuredFieldDecision: (journalId) => ipcRenderer.invoke('archive:undoStructuredFieldDecision', { journalId })
}

contextBridge.exposeInMainWorld('archiveApi', archiveApi)
